// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type NewUser struct {
	Name     string  `json:"name"`
	Nickname *string `json:"nickname"`
}

type Todo struct {
	ID         int    `json:"id"`
	Text       string `json:"text"`
	IsFinished bool   `json:"isFinished"`
	User       *User  `json:"user"`
}

type User struct {
	ID       int     `json:"id"`
	Name     string  `json:"name"`
	Nickname *string `json:"nickname"`
}
