version: "3.6"
services:
  mysql:
    image: mysql:5.7
    container_name: "toolbox-go-transactions"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toolbox-go-transactions

volumes:
  mysql-data:
    name: toolbox-go-transactions
