version: "3.6"
services:
  mysql:
    image: mysql:5.7
    container_name: "mysql-full-stack-todo"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-full-stack-todo

volumes:
  mysql-data:
    name: mysql-full-stack-todo
