CREATE TABLE IF NOT EXISTS list(
    id INT AUTO_INCREMENT,
    uid VARCHAR(32) UNIQUE NOT NULL,
    name VARCHAR(32) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS todo(
    id INT AUTO_INCREMENT,
    uid VARCHAR(32) UNIQUE NOT NULL,
    `text` VARCHAR(1080) NOT NULL,
    is_finished BOOLEAN NOT NULL DEFAULT 0,
    list_id INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(list_id) REFERENCES list(id) ON DELETE CASCADE
)
